### ISSUE TITLE
installing metafor

### ISSUE THREAD

**Issue by elecarnero** [wviechtb/metafor#1]
Hi, I am having troubles installing the metafor R package.
Here is the error I am encountering:

Installing package(s) 'metafor'
Warning: unable to access index for repository https://cran.rstudio.com/src/contrib:
  unsupported URL scheme
Warning: unable to access index for repository https://cran.rstudio.com/src/contrib:
  unsupported URL scheme
Warning message:
package ‘metafor’ is not available (for R version 3.2.3) 

Any help on how to solve this issue would be highly appreciated.
Thanks in advance,
Elena

**Comment by jamesfreinhardt** [comment]
My suggestion would be to change the mirror in which to download the package from.  
try the function: chooseCRANmirror()

or see
https://stat.ethz.ch/R-manual/R-devel/library/utils/html/chooseCRANmirror.html

**Comment by wviechtb** [comment]
I just tried `install.packages(metafor)` on Windows (R 3.2.3) using the "Cloud" mirror (which is https://cran.rstudio.com) and that worked without any problems. You seem to be trying to install from source, but https://cran.rstudio.com/src/contrib/metafor_1.9-8.tar.gz is there, so I don't know what the problem is. But this doesn't seem to be an issue related to `metafor` but rather some issue with your local setup.
