### ISSUE TITLE
RE: forest() atransf

### ISSUE THREAD

**Issue by DanBaiS** [wviechtb/metafor#12]
I used forest() to draw forest plot of several proportions. I used atransf = mytransf to show annotation in percentage, below is mytransf:
mytransf <- function(x, digits = 0, format = "f", ...) {
  paste0(formatC(100 * x, format = format, digits = digits, ...), "%")
}
This works fine, but with flip the order of 95% CI like below:
15% [26%, 5%], which should be 15%[5%, 26%]. 
I realized it's because the system treated this two numbers as strings, but I don't know how to change it in the order I wanted.
I also tried the simple atransf=percent by calling from library scales, not working.
Could you help with this? Many thanks.

**Comment by wviechtb** [comment]
Whoa, I am surprised that `atransf` works with this. Nice to see that it does. And indeed, because `forest()` wants to ensure that the CI bounds are always sorted in increasing order after applying some transformation, this actually goes wrong here since `sort(c("5%", "26%"))` does exactly NOT what we want. A somewhat hackish solution is to overwrite the internal function in `metafor` that does the sorting (it is a non-exported function called `metafor:::.psort`) with a version that just doesn't sort. Here is an example that shows how to do this:

```
library(metafor)

dat <- data.frame(xi = c(20, 40, 5), ni = c(40, 80, 50))
dat <- escalc(measure="PR", xi=xi, ni=ni, data=dat)
res <- rma(yi, vi, data=dat)

mytransf <- function(x, digits = 0, format = "f", ...)
   paste0(formatC(100 * x, format = format, digits = digits, ...), "%")

forest(res, atransf=mytransf)

.mypsort <- function(x,y) {
   if (missing(y)) {
      if (is.matrix(x)) {
         xy <- x
      } else {
         xy <- rbind(x)
      }
   } else {
      xy <- cbind(x,y)
   }
   return(xy)
}

assignInNamespace(".psort", .mypsort, ns="metafor")

forest(res, atransf=mytransf)
```

**Comment by DanBaiS** [comment]
Thank you so much! This works perfectly.
