### ISSUE TITLE
Output only the 

### ISSUE THREAD

**Issue by apacheark** [wviechtb/metafor#16]
I am just now learning to use the metafor package.  Thanks for hard work; it is a very useful package.

On the page: http://www.metafor-project.org/doku.php/plots:forest_plot_with_subgroups
the example shows the output of the forest plot.  I was trying to find a way to output ONLY the summary statistics information for "RE Model for All Studies" and the corresponding plot for that summary.
I would like to be able to turn off the output of the  individual studies and just show the stats and plot for the summarized information.
Is there a way to accomplish that?

Thank you.
-Anand

**Comment by wviechtb** [comment]
I don't quite understand what you are trying to do. You just want a plot of a single summary polygon (with the text around it) for the RE model of all studies and nothing else?

**Comment by apacheark** [comment]
Hi.  Yes, that's the idea. I managed to get close to what I want by
changing the forest command to the following.  This outputs only the
summary line and the corresponding diamond.
I think am essentially only outputting the rows with the data I want by
limiting the ylim values.  Is that right?  Is there a more elegant way to
do this? Thank you.

forest <http://finzi.psych.upenn.edu/library/metafor/html/forest.html>(res,
xlim=c <http://stat.ethz.ch/R-manual/R-devel/library/base/html/c.html>(-16,
6), at=log <http://stat.ethz.ch/R-manual/R-devel/library/base/html/log.html>(c
<http://stat.ethz.ch/R-manual/R-devel/library/base/html/c.html>(0.05,
0.25, 1, 4)), atransf=exp
<http://stat.ethz.ch/R-manual/R-devel/library/base/html/exp.html>,
       ilab=cbind
<http://stat.ethz.ch/R-manual/R-devel/library/base/html/cbind.html>(dat.bcg$tpos,
dat.bcg$tneg, dat.bcg$cpos, dat.bcg$cneg),
       ilab.xpos=c
<http://stat.ethz.ch/R-manual/R-devel/library/base/html/c.html>(-9.5,-8,-6,-4.5),
cex=0.75, ylim=c
<http://stat.ethz.ch/R-manual/R-devel/library/base/html/c.html>(-1,
0),
       xlab="Risk Ratio", mlab="", psize=1)

**Comment by apacheark** [comment]
I updated the code snippet which I had horribly mangled.

**Comment by wviechtb** [comment]
Have you worked through all of the examples in `help(forest.rma)`, help(forest.default)`, help(addpoly.rma)`, and `help(addpoly.default)`? In essence, the forest and addpoly functions provide all of the functionality to put together any kind of plot you would want. Almost everything can be customized as explained in the help files to these functions. And since these are base graphics plots, you can add any other elements you would like using functions such as `points()`, `text()`, and so on. So, yes, what you are asking for is possible, but you have to read the help files and play around with the functions to understand how they work and what can be done.

**Comment by wviechtb** [comment]
I assume this issue is now resolved.
