### ISSUE TITLE
rma.glmm example fails

### ISSUE THREAD

**Issue by reikoch** [wviechtb/metafor#26]
On RHEL 7.6 with version 2.0-0 the last example in metafor/pritz1997.Rd fails with

```
> ### mixed-effects logistic regression model
> res <- rma.glmm(measure="PLO", xi=xi, ni=ni, data=dat)
Error in t(b2.QE) %*% chol2inv(chol.h) : non-conformable arguments
Calls: rma.glmm
Execution halted
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ... ERROR
  Running ‘testthat.R’
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  4: withCallingHandlers(code, warning = function(condition) {
         out$push(condition)
         invokeRestart("muffleWarning")
     })
  5: eval_bare(get_expr(quo), get_env(quo))
  6: rma.glmm(measure = "PLO", xi = xi, ni = ni, mods = ~mod1, data = dat)
```
whereas on Windows 10 the example runs producing a warning though:
```
4: In rma.glmm(measure = "PLO", xi = xi, ni = ni, data = dat) :
  Cannot invert Hessian for saturated model.
```
Is rma.glmm touching numerical limits here?

Kind regards
Reinhold

**Comment by wviechtb** [comment]
I just tried this example with Ubuntu 16.04 and Windows 7 and both run without any errors or warnings. Can you post your sessionInfo()?

**Comment by reikoch** [comment]
Sure. Just tried again and got:
```
> library(metafor) 
> dat <- dat.pritz1997 
> res <- rma.glmm(measure="PLO", xi=xi, ni=ni, data=dat) 
Error in t(b2.QE) %*% chol2inv(chol.h) : non-conformable arguments 
> sessionInfo() 
R version 3.5.3 (2019-03-11)
Platform: x86_64-pc-linux-gnu (64-bit) 
Running under: Red Hat Enterprise Linux  
Matrix products: default 
BLAS/LAPACK: /usr/lib64/libopenblas-r0.2.20.so 
 locale:  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8
         [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
     [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C
               [10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C
attached base packages: 
[1] stats     graphics  grDevices utils     datasets  methods   base       
other attached packages: 
[1] metafor_2.0-0 Matrix_1.2-17 meta_4.9-5     
loaded via a namespace (and not attached):  
[1] minqa_1.2.4     MASS_7.3-51.3   compiler_3.5.3  tools_3.5.3     yaml_2.2.0       
[6] Rcpp_1.0.1      splines_3.5.3   nlme_3.1-139    grid_3.5.3      nloptr_1.2.1    
[11] boot_1.3-20     lme4_1.1-21     lattice_0.20-38
```
I thought this is a very standard RHEL 7.6 installation.

P.S. on MacOS 10.14.4 with R 3.5.2 I do get a fit, but with a warning "Cannot invert Hessian for saturated model."

**Comment by wviechtb** [comment]
Hmmm, looks fine to me. I see that the OpenBLAS tests on CRAN are also throwing the same error: https://www.stats.ox.ac.uk/pub/bdr/Rblas/OpenBLAS/metafor.out But I actually run OpenBLAS here myself and get no error. My sessionInfo() looks slightly different though:

    Matrix products: default
    BLAS: /usr/lib/openblas-base/libblas.so.3
    LAPACK: /usr/lib/libopenblasp-r0.2.18.so

So I have separate libs for BLAS and LAPACK, while you seem to use `libopenblas-r0.2.20.so` for both. No idea if this is related or what this implies.

In essence though, what is happening is that there is a mismatch in the number of non-aliased coefficients for the saturated model and the dimensions of the corresponding var-cov matrix. There was actually a change in the behavior of `vcov.glm()` starting in R version 3.5.0 with regard to this (that initially caused `rma.glmm()` to fail consistently), but I fixed that a long time ago. I assume you did a recent `devtools::install_github("wviechtb/metafor")` so that can't be it. The problem with the var-cov matrix may also come a bit later where I take a Cholesky decomposition of it with `chol()` followed by `chol2inv()`, so maybe the dimensions get messed up there. It's really difficult to diagnose/fix this without access to a machine that shows this behavior. What I can do for sure though is check for a dimension mismatch and if so, skip the calculation that is happening there (which is non-essential for the actual model fit; it only pertains to the Wald-type heterogeneity test). The warning you got with MacOS is related; the attempt to use `chol()` fails, but this is caught and things continue.

**Comment by reikoch** [comment]
For easier reproducibility I turned to rocker/rstudio docker image, currently based on R 3.5.3.
With current CRAN release of metafor 2.0-0 I got the same errors:
```
> rma.glmm(measure = "PLO", xi = xi, ni = ni, data = dat.pritz1997)
Error in t(b2.QE) %*% chol2inv(chol.h) : non-conformable arguments
> sessionInfo()
R version 3.5.3 (2019-03-11)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 9 (stretch)

Matrix products: default
BLAS: /usr/lib/openblas-base/libblas.so.3
LAPACK: /usr/lib/libopenblasp-r0.2.19.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C             
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] metafor_2.0-0 Matrix_1.2-15

loaded via a namespace (and not attached):
 [1] minqa_1.2.4     MASS_7.3-51.1   compiler_3.5.3  tools_3.5.3     Rcpp_1.0.1     
 [6] splines_3.5.3   nlme_3.1-137    grid_3.5.3      nloptr_1.2.1    boot_1.3-20    
[11] lme4_1.1-21     lattice_0.20-38
```
so the issue is not Redhat/CentOS.
Upgrading to your current version 2.1-0 on github solved the issue though:
```
> rma.glmm(measure = "PLO", xi = xi, ni = ni, data = dat.pritz1997)

Random-Effects Model (k = 14; tau^2 estimator: ML)

tau^2 (estimated amount of total heterogeneity): 0.5893
tau (square root of estimated tau^2 value):      0.7677
I^2 (total heterogeneity / total variability):   67.7897%
H^2 (total variability / sampling variability):  3.1046

Tests for Heterogeneity:
Wld(df = 13) = 25.0979, p-val = 0.0224
LRT(df = 13) = 42.2324, p-val < .0001

Model Results:

estimate      se    zval    pval   ci.lb   ci.ub 
  1.3766  0.2884  4.7735  <.0001  0.8114  1.9418  *** 

---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
```
Maybe it is time to release 2.1?

**Comment by wviechtb** [comment]
Ah, ok, so this is indeed due to the change in `vcov.glm()`. Okay, will release a new CRAN version soon.

**Comment by wviechtb** [comment]
Done, so closing this issue now.
