### ISSUE TITLE
Failed to update package V.2.1.0

### ISSUE THREAD

**Issue by Qingys** [wviechtb/metafor#27]
Hello,
I failed when I tried to update version 2.1.0 through "install_github("wviechtb/metafor")". 
It mentioned:

Installing package into ‘C:/Users/Qingy/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package 'metafor' ...
** R
Error : (由警告转换成)无法重新编码'misc.func.hidden.r'行2359
ERROR: unable to collate and parse R files for package 'metafor'
* removing 'C:/Users/Qingy/Documents/R/win-library/3.5/metafor'
* restoring previous 'C:/Users/Qingy/Documents/R/win-library/3.5/metafor'
In R CMD INSTALL
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/Qingy/AppData/Local/Temp/RtmpMT0FZ7/file15b41944810/metafor_2.1-0.tar.gz’ had non-zero exit status

sessionInfo():
R version 3.5.2 (2018-12-20)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936 
[2] LC_CTYPE=Chinese (Simplified)_China.936   
[3] LC_MONETARY=Chinese (Simplified)_China.936
[4] LC_NUMERIC=C                              
[5] LC_TIME=Chinese (Simplified)_China.936    

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] bindrcpp_0.2.2    dplyr_0.7.6       forestmodel_0.5.0 ggplot2_3.1.1    
[5] usethis_1.4.0     devtools_2.0.1    forestplot_1.7.2  checkmate_1.8.5  
[9] magrittr_1.5     

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.18      bindr_0.1.1       compiler_3.5.2    pillar_1.3.1     
 [5] plyr_1.8.4        prettyunits_1.0.2 remotes_2.0.2     tools_3.5.2      
 [9] digest_0.6.16     pkgbuild_1.0.2    pkgload_1.0.2     memoise_1.1.0    
[13] tibble_1.4.2      gtable_0.2.0      pkgconfig_2.0.2   rlang_0.3.1      
[17] cli_1.0.1         rstudioapi_0.7    curl_3.2          yaml_2.2.0       
[21] withr_2.1.2       desc_1.2.0        fs_1.2.6          tidyselect_0.2.4 
[25] rprojroot_1.3-2   glue_1.3.0        R6_2.2.2          processx_3.2.1   
[29] sessioninfo_1.1.1 purrr_0.2.5       callr_3.1.1       backports_1.1.2  
[33] scales_1.0.0      ps_1.3.0          assertthat_0.2.0  colorspace_1.3-2 
[37] lazyeval_0.2.1    munsell_0.5.0     crayon_1.3.4 

What can I do for this situation ? 
PS. The characters, "无法重新编码", means “Unable to recode”; "行", "row".

**Comment by wviechtb** [comment]
I just tried under Windows 7 with R 3.5.3 and it installed without problems. Maybe try updating your version of R (the current one is 3.6.0). Could also be some kind of encoding issue, but before I would go down that route, first try updating R.

**Comment by Qingys** [comment]
You are right! It succeeds after updating R to 3.6.0. 
And there are another error mention:  

Error in substring(html, match + 6, match + attr(match, "match.length") -  : 
  invalid multibyte string at '<a2><<2f>i> denote the observed value of the effect size or outcome measure in the <i>i</i>th study. Let <i>&theta;岬<a2></i> denote the corresponding (unknown) true effect or outcome, such that </p>
<p style="text-align: center;"><i>y岬<a2> | &theta;岬<a2> ~ N(&theta;岬<a2>, v岬<a2>).</i></p>
<p> In other words, the observed effects or outcomes are assumed to be unbiased and normally distributed estimates of the corresponding true effects or outcomes with sampling variances equal to <i>v岬<a2></i>. The <i>v岬<a2></i> values are assumed to be known. Depending on the outcome measure used, a bias correction, normalizing, and/or variance stabilizing transformation may be necessary to ensure that these assumptions are (approximately) true (e.g., the log transformation for odds ratios, the bias correction for standardized mean differences, Fisher's r-to-z transformation for correlations; see <code><a href="../../metafor/help/escalc">escalc</a></code> f

However, this error seem to not affect usage. Should I take measures to handle it or ignore it?

**Comment by wviechtb** [comment]
Most importantly, it installs, so happy to hear that.

What you are encountering now is some kind of encoding issue with some help files. I make use of some unicode characters in the help files for a nicer display of some equations in the HTML documentation. For example, those 岬 symbols should be subscript i. You can see what this is supposed to look like here:

http://finzi.psych.upenn.edu/library/metafor/html/metafor-package.html

But if you have the same issue with your browser (if the problem isn't just specific to R, but more generally affects your OS), then you might see garbled up symbols there as well. You can also browse the documentation here:

https://wviechtb.github.io/metafor/reference/metafor-package.html

The display of equations is even nicer there, since this makes use of MathJax to show the LaTeX equations.

In the end, this problem should only affect your ability to read the help files locally. How does it look if you do `help(metafor)`? Do you also see garbled up symbols there as well?

**Comment by Qingys** [comment]
I tried these two HTML documentation and "help(metafor)". All of these are normal and none garbled up symbol was seen. Only in R console interface will see this error. Is it a possibility that caused by Chinese language based R or Rstudio ?

**Comment by wviechtb** [comment]
When you say that "Only in R console interface will see this error", do you mean during the installation via `install_github("wviechtb/metafor")`? If so, what happens if you install the CRAN version via `install.packages("metafor")`? And yes, I assume it has something to do with your language settings.

**Comment by Qingys** [comment]
The error appears during the process on loading "metafor". I tried this in RGui and this error disappears. So I think this error is caused by Rstudio. Luckily, it not affect usage and this package is powerful as always.
Thank you very much for all these help.
