### ISSUE TITLE
vtype = AV

### ISSUE THREAD

**Issue by Stach5** [wviechtb/metafor#87]
## Classification:

Question/bug

## Summary

Using the escalc function, with measure = MN, I receive an error when I choose AV for vtype. 
My colleague is able to use vtype = AV for this measure, but I receive the error that vtype must be either LS or HO. 

```r

Z_test<-
  Z_test %>% 
  escalc(ni = Z_test$n_patients, mi = Z_test$mean_zscore, sdi = Z_test$sd_zscore, vtype = "AV", data = ., measure = "MN", append = TRUE)

Error in escalc(ni = Z_test$n_patients, mi = Z_test$mean_zscore, sdi = Z_test$sd_zscore,  : 
  For this outcome measure, 'vtype' must be either 'LS' or 'HO'.

**Comment by wviechtb** [comment]
For this measure, `vtype="AV"` has never been an option. This wouldn't make any sense to begin with, since the sampling variance is not a function of the outcome itself. I would have to start digging through the code of older version to check this, but maybe `vtype` was simply ignored in the past for this measure.
