### ISSUE TITLE
Problem with forest() in version 2.0.0

### ISSUE THREAD

**Issue by jscamac** [wviechtb/metafor#9]
I've recently installed R 3.4.1 and updated metafor to 2.0.0 and I've found the following error when running `forest(rma_object)`
```
Error in object$X.f %*% object$beta : 
  requires numeric/complex matrix/vector arguments
```

I managed to get it to work when I reverted back to 1.9-9.

**Comment by wviechtb** [comment]
Can you provide a fully reproducible example? I cannot replicate this problem. One possibility: If you have a model object from an older version, it might not work with the most recent version due to some changes in the naming of the list elements (in the `rma_object`). In that case, refitting the model should solve the problem.

**Comment by jscamac** [comment]
Sorry I forgot to respond to this. Yes it looked like I had some old rma object still in the environment which was causing this error. Cheers
